version: "3"
services:
  django_in_amw:
    build: ./
    image: django_in_apache_modwsgi:1.0.0
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      - ./src:/develop
    working_dir: /develop
